### ISSUE TITLE
Todo list for calculating anomaly forcing

### ISSUE THREAD

**Issue by kjetilaas** [kjetilaas/PathFinder_WP3_Task3.5_scripts#1]
- [x] Download monthly cordex data
- [x] calculate baseline mean climate
- [x] split downloaded data by year
- [x] subtract baseline climatology
- [x] merge years and calculate running mean of monthly values (probably need to include baseline years)
- [x] make plots
- [x] push code and figures to github
